### ISSUE TITLE
깃플로우 사용해서 브랜치 만들어서 작업 해주세요

### ISSUE THREAD

**Issue by kimjeongwonn** [kyupkyup/timer-practice#1]
부탁드려용 ^^

**Comment by kimjeongwonn** [comment]
그리고 prettier설정 파일 하나 만들고 시작해야 할것같아요

**Comment by kimjeongwonn** [comment]
{
  "singleQuote": true,
  "semi": true,
  "useTabs": false,
  "tabWidth": 2,
  "trailingComma": "all",
  "printWidth": 80,
  "arrowParens": "avoid",
  "endOfLine": "auto"
}


prettier 셋팅 부탁드려요...

**Comment by kyupkyup** [comment]
일단 초기화 한거 푸쉬하고 셋팅 커밋 따로 제작하겠삼

**Comment by kimjeongwonn** [comment]
> 일단 초기화 한거 푸쉬하고 셋팅 커밋 따로 제작하겠삼

알겠읍니다 ^^
