### ISSUE TITLE
ms 타이머로 표현하는 수식 짰으면 공유좀 부탁드려요...

### ISSUE THREAD

**Issue by kimjeongwonn** [kyupkyup/timer-practice#10]
짱구가 안굴러가네요 ^^,,

**Comment by kyupkyup** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

**Comment by kyupkyup** [comment]
코드 푸쉬했습니당 확인점

**Comment by kimjeongwonn** [comment]
> 코드 푸쉬했습니당 확인점

감삼다 ^^~!

**Comment by ulgoon** [comment]
자주 푸쉬하시구 PR 날리시면 좋을 것 같습니다^^

**Comment by kimjeongwonn** [comment]
> 코드 푸쉬했습니당 확인점

안올라와 있어요 ㅠㅠ

**Comment by kyupkyup** [comment]
브랜치 렌더 어쩌구 확인하면될듯요. develop엔 안 올라와있어요 아직

**Comment by kimjeongwonn** [comment]
> 어 죄송 닫아버렸넹. develop 푸쉬할게요~

호호 감삼다 ㅋ

**Comment by kyupkyup** [comment]
devevlop에 푸쉬했어요
