### ISSUE TITLE
리드미 제작

### ISSUE THREAD

**Issue by kyupkyup** [kyupkyup/timer-practice#11]
제가 하겠슴다

**Comment by kimjeongwonn** [comment]
넵... 글구 수식 올린 코드가 아직 푸쉬가 안되어있는듯 하옵니다. ..

**Comment by kimjeongwonn** [comment]
브랜치가 없어요 원격레포에 . . .

**Comment by kyupkyup** [comment]
develop에 올렸슴다

**Comment by kyupkyup** [comment]
리드 미 제작 완료 피드백은 여기로 주세용

**Comment by kimjeongwonn** [comment]
> 리드 미 제작 완료 피드백은 여기로 주세용

리드미 귀엽고 좋네요 ^^b

**Comment by ProgWon** [comment]
> > 리드 미 제작 완료 피드백은 여기로 주세용
> 
> 리드미 귀엽고 좋네요 ^^b

저는 정원님이 더 귀여워요.. 후후..

**Comment by kyupkyup** [comment]
> > > 리드 미 제작 완료 피드백은 여기로 주세용
> > 
> > 
> > 리드미 귀엽고 좋네요 ^^b
> 
> 저는 정원님이 더 귀여워요.. 후후..

ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ
