### ISSUE TITLE
feat: 리셋 버튼 기능 추가

### ISSUE THREAD

**Issue by kimjeongwonn** [kyupkyup/timer-practice#13]
- 타이머 초기화
- lap 초기화

**Comment by kimjeongwonn** [comment]
풀리퀘가 왜 안만들어 질까요...  There isn’t anything to compare.가 뜨네요 ㅠㅠ

**Comment by kyupkyup** [comment]
아까 풀리퀘 이후로 커밋 추가로 했삼?

**Comment by kimjeongwonn** [comment]
> 아까 풀리퀘 이후로 커밋 추가로 했삼?

당근 빳다지 그 깃플로우 finish 한건데... 추가가 안되네요

**Comment by kimjeongwonn** [comment]
> 아까 풀리퀘 이후로 커밋 추가로 했삼?

하다 보니까 됐다요 ㅋ

**Comment by ProgWon** [comment]
> > 아까 풀리퀘 이후로 커밋 추가로 했삼?
> 
> 당근 빳다지 그 깃플로우 finish 한건데... 추가가 안되네요

당근당근 바니바니바니바니 당근당근
