### ISSUE TITLE
프로젝트 카드 어떻게 할지 생각해볼까요

### ISSUE THREAD

**Issue by kimjeongwonn** [kyupkyup/timer-practice#2]
- 타임워치 마크업 및 상태정의
- start 할 때 동작
- start 이후 버튼 기능변경
- stop/resume 토글 기능
- lap 버튼으로 현재 타임워치 상태 가져오기
- 가져온 상태 DOM에 추가하기
- reset 버튼을 통해 모든상태 초기화

이정도 어떨까요

**Comment by kyupkyup** [comment]
넹

**Comment by kyupkyup** [comment]
근데 너가 파일 만들어서 작업 시작해야 될듯 나 커밋 메시지가 저장이 안된다 개빡치네

**Comment by kimjeongwonn** [comment]
띠용 왜지 일단 ㅇㅋ

**Comment by kyupkyup** [comment]
커밋메시지 지정하는거 해결했구, 프로젝트 카드 만들껨

**Comment by kimjeongwonn** [comment]
옙 각자 자기가 할 일 이슈에 올려서 실시간으로 하면 될듯합니다~
