### ISSUE TITLE
prettierrc 까지 추가해주면 풀받을게용

### ISSUE THREAD

**Issue by kimjeongwonn** [kyupkyup/timer-practice#4]
부탁드립니다~

**Comment by kimjeongwonn** [comment]
{
"singleQuote": true,
"semi": true,
"useTabs": false,
"tabWidth": 2,
"trailingComma": "all",
"printWidth": 80,
"arrowParens": "avoid",
"endOfLine": "auto"
}

**Comment by kyupkyup** [comment]
오키

**Comment by kyupkyup** [comment]
푸쉬함~
