### ISSUE TITLE
프로젝트 카드 추가 완료

### ISSUE THREAD

**Issue by kyupkyup** [kyupkyup/timer-practice#8]

**Comment by kyupkyup** [comment]
라벨도 추가해놨으니 DOM이랑 함수 관련 이슈는 따로 추가 해 주삼!

**Comment by kimjeongwonn** [comment]
라벨은 제가 추가 별도로 못해요...

**Comment by kyupkyup** [comment]
> 라벨은 제가 추가 별도로 못해요...
콜라보레이터 추가해놨는데 확인 부탁용

**Comment by kimjeongwonn** [comment]
> 라벨은 제가 추가 별도로 못해요...
> >콜라보레이터 추가해놨는데 확인 부탁용

강사님이 콜라보레이터로 작업하면 박제한다고 했어요... ^^

**Comment by kyupkyup** [comment]
엌ㅋㅋㅋ

**Comment by kyupkyup** [comment]
그럼 라벨 추가할 거 있으면 말해주세요 ㅋㅋㅋ

**Comment by kimjeongwonn** [comment]
> 그럼 라벨 추가할 거 있으면 말해주세요 ㅋㅋㅋ

일단 아래있는 내용 부탁드려욥,,,

**Comment by kimjeongwonn** [comment]
> 그럼 라벨 추가할 거 있으면 말해주세요 ㅋㅋㅋ

#7 이 이슈

**Comment by kyupkyup** [comment]
프로젝트랑 라벨 등록 다 해뒀는딩? 라벨은 DOM 이랑 함수 라벨 등록해뒀구 추가로 해야될 것 있으면 ㅋㅋ 프로젝트도 등록함

**Comment by kimjeongwonn** [comment]
> 프로젝트랑 라벨 등록 다 해뒀는딩? 라벨은 DOM 이랑 함수 라벨 등록해뒀구 추가로 해야될 것 있으면 말해주면됨 ㅋㅋ 프로젝트도 등록함

이슈에 프로젝트랑 라벨 할당해줘야 연동이 되는걸로 알고있어유~
레포 관리자만 할 수 있는거라 내가 못함 ㅠㅠ

**Comment by kyupkyup** [comment]
> > 프로젝트랑 라벨 등록 다 해뒀는딩? 라벨은 DOM 이랑 함수 라벨 등록해뒀구 추가로 해야될 것 있으면 말해주면됨 ㅋㅋ 프로젝트도 등록함
> 
> 이슈에 프로젝트랑 라벨 할당해줘야 연동이 되는걸로 알고있어유~
> 레포 관리자만 할 수 있는거라 내가 못함 ㅠㅠ

아하 이제 이해함ㅋㅋ 추가했습니다~

**Comment by kimjeongwonn** [comment]
> > > 프로젝트랑 라벨 등록 다 해뒀는딩? 라벨은 DOM 이랑 함수 라벨 등록해뒀구 추가로 해야될 것 있으면 말해주면됨 ㅋㅋ 프로젝트도 등록함
> > 
> > 
> > 이슈에 프로젝트랑 라벨 할당해줘야 연동이 되는걸로 알고있어유~
> > 레포 관리자만 할 수 있는거라 내가 못함 ㅠㅠ
> 
> 아하 이제 이해함ㅋㅋ 추가했습니다~

굳ㅋ 근데 그 프로젝트 설정에서 이슈랑 연결되면 자동으로 등록되게 설정해줘야 할듯 자동등록 안된 거 보니까...?
그래야 이슈 닫히면 알아서 Done으로 이동하는 거 같어, 나는 Project도 관리할 수가 없음...

**Comment by ulgoon** [comment]
> > > > 프로젝트랑 라벨 등록 다 해뒀는딩? 라벨은 DOM 이랑 함수 라벨 등록해뒀구 추가로 해야될 것 있으면 말해주면됨 ㅋㅋ 프로젝트도 등록함
> > > 
> > > 
> > > 이슈에 프로젝트랑 라벨 할당해줘야 연동이 되는걸로 알고있어유~
> > > 레포 관리자만 할 수 있는거라 내가 못함 ㅠㅠ
> > 
> > 
> > 아하 이제 이해함ㅋㅋ 추가했습니다~
> 
> 굳ㅋ 근데 그 프로젝트 설정에서 이슈랑 연결되면 자동으로 등록되게 설정해줘야 할듯 자동등록 안된 거 보니까...?
> 그래야 이슈 닫히면 알아서 Done으로 이동하는 거 같어, 나는 Project도 관리할 수가 없음...

네 기본적으로 그렇게 동작하며 pull request가 main 브랜치에 반영되어도 이동합니다^^
